### ISSUE TITLE
bug(CI/CD): contributor history

### ISSUE THREAD

**Issue by twilson63** [twilson63/permaweb-cookbook#85]
To solve the contributor history issue for gh actions - 
- depth should be full for now. 

``` yml
- uses: actions/checkout@v3
  with:
    fetch-depth: 0

```

By setting fetch-depth to 0 it will pull all branches and should properly add contributor info to each article
